### ISSUE TITLE
OutOfMemoryError in PixelBuffer.convertToBitmap  

### ISSUE THREAD

**Issue by rakeshbhatt10** [CyberAgent/android-gpuimage#168]
Hi,

I am using your library. Currently your implementation works fine but after regressive testing i am getting below exception. I am still unable to figure out original cause of this problem. Please help  !!

at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.OutOfMemoryError
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:928)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:901)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:868)
	at jp.co.cyberagent.android.gpuimage.PixelBuffer.convertToBitmap(PixelBuffer.java:204)
	at jp.co.cyberagent.android.gpuimage.PixelBuffer.getBitmap(PixelBuffer.java:123)
	at jp.co.cyberagent.android.gpuimage.GPUImage.getBitmapWithFilterApplied(GPUImage.java:282)
	at jp.co.cyberagent.android.gpuimage.GPUImage$SaveTask.doInBackground(GPUImage.java:404)
	at jp.co.cyberagent.android.gpuimage.GPUImage$SaveTask.doInBackground(GPUImage.java:1)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)

**Comment by vashisthg** [comment]
Your image is too large causing out of memory error. Please check if there is any memory leak happening in your project.

**Comment by rakeshbhatt10** [comment]
Hi @vashisthg 

Thanks for your reply

I am capturing image with lowest resolution possible i.e. 640x480 for memory leak i will check into my project and let you know
