### ISSUE TITLE
no libgpuimage.so

### ISSUE THREAD

**Issue by pierrexn** [CyberAgent/android-gpuimage#248]
it seems that libgpuimage is not build in 1.3.0

i have no libguimage.so when using compile 'jp.co.cyberagent.android.gpuimage:gpuimage-library:1.3.0'

compile 'jp.co.cyberagent.android.gpuimage:gpuimage-library:1.2.3' works...

**Comment by dockusan** [comment]
I compile with 1.3.0 and it works. Please check it again

**Comment by vimaldiwani** [comment]
Facing same problem. Any help will be appreciated.

**Comment by filipst** [comment]
Any help with this?

**Comment by dockusan** [comment]
![ndk](https://cloud.githubusercontent.com/assets/10556072/13489169/170febf4-e158-11e5-905d-3225996dfd79.png)
I download NDK from [this](http://developer.android.com/intl/vi/ndk/index.html) and add ndk link to local.properties

**Comment by filipst** [comment]
I have same ndk-r10e and it is not working when I include this library in my project.

**Comment by dockusan** [comment]
What wrong you get when build gradle?

**Comment by filipst** [comment]
I have included library like this in my build.gradle file
`compile 'jp.co.cyberagent.android.gpuimage:gpuimage-library:1.3.0'`
And when I try to use CameraActivity like in "sample" I get error:
`03-03 09:38:33.391 19409-19450/com.test E/AndroidRuntime: FATAL EXCEPTION: GLThread 1018
                                                                 Process: com.test, PID: 19409
                                                                 java.lang.UnsatisfiedLinkError: Couldn't load gpuimage-library from loader dalvik.system.PathClassLoader[dexPath=/data/app/com.test-14.apk,libraryPath=/data/app-lib/com.test-14]: findLibrary returned null
                                                                     at java.lang.Runtime.loadLibrary(Runtime.java:358)
                                                                     at java.lang.System.loadLibrary(System.java:526)
                                                                     at jp.co.cyberagent.android.gpuimage.GPUImageNativeLibrary.<clinit>(GPUImageNativeLibrary.java:21)
                                                                     at jp.co.cyberagent.android.gpuimage.GPUImageRenderer$1.run(GPUImageRenderer.java:141)
                                                                     at jp.co.cyberagent.android.gpuimage.GPUImageRenderer.runAll(GPUImageRenderer.java:126)
                                                                     at jp.co.cyberagent.android.gpuimage.GPUImageRenderer.onDrawFrame(GPUImageRenderer.java:115)
                                                                     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
                                                                     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
`

**Comment by dockusan** [comment]
I download and put library as module and it works fine. Please download it

**Comment by filipst** [comment]
Now I get 

`Error:No such property: GROUP for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer`

**Comment by dockusan** [comment]
Download 
https://drive.google.com/file/d/0B-oJn4fBmlDbajlKdUF3ZkQ0Tzg/view?usp=sharing
and replace all file in this picture.
![library1](https://cloud.githubusercontent.com/assets/10556072/13490796/13c3fe28-e161-11e5-8a5c-57b3100900c8.png)

**Comment by filipst** [comment]
Works like a charm. I am very grateful. Thank you.

**Comment by dockusan** [comment]
You're most welcome. :smile:

**Comment by vimaldiwani** [comment]
I followed the above step but the problem still persist for me.

Couldn't load gpuimage-library from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.getMe.GetMe.apk-1"],nativeLibraryDirectories=[/data/app-lib/com.getMe.GetMe.apk-1, /vendor/lib, /system/lib]]]: findLibrary returned null

**Comment by filipst** [comment]
I am getting that error again. Nothing helps.

**Comment by Freshman111** [comment]
I download this project and import to my Android studio.But I got this error.If anyone faced and solved this problem
![20160414120708](https://cloud.githubusercontent.com/assets/9150631/14516824/89cfb564-0239-11e6-9f76-4c0123c048d5.png)

**Comment by Freshman111** [comment]
I don't know the reason,but I solved it by change the build.gradle file of the library module
hope to helpful for others

abiFilters "all"-------->abiFilters "armeabi", "armeabi-v7a", "x86"

ndk {
            moduleName "gpuimage-library"
            stl "gnustl_shared"
            abiFilters "armeabi", "armeabi-v7a", "x86"
            ldLibs "log"
        }

**Comment by SohailZahidGit** [comment]
compile 'jp.co.cyberagent.android.gpuimage:gpuimage-library:1.2.3' it really works..
