### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: junit/textui/ResultPrinter

### ISSUE THREAD

**Issue by cs8** [CyberAgent/android-gpuimage#294]
after download the android NDK i run the project,it's show this in the run zoom;
I don't know how to do next step.
Any suggestion?

/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/bin/java -ea -Didea.launcher.port=7536 "-Didea.launcher.bin.path=/Applications/Android Studio.app/Contents/bin" -Didea.junit.sm_runner -Dfile.encoding=UTF-8 -classpath "/Applications/Android Studio.app/Contents/lib/idea_rt.jar:/Applications/Android Studio.app/Contents/plugins/junit/lib/junit-rt.jar:/Users/chen/Library/Android/sdk/platforms/android-23/data/res:/Users/chen/work/github/android/android-gpuimage/sample/build/intermediates/classes/debug:/Users/chen/work/github/android/android-gpuimage/sample/build/intermediates/exploded-aar/com.android.support/support-v4/23.1.1/jars/libs/internal_impl-23.1.1.jar:/Users/chen/work/github/android/android-gpuimage/sample/build/intermediates/exploded-aar/com.android.support/support-v4/23.1.1/jars/classes.jar:/Users/chen/work/github/android/android-gpuimage/sample/build/intermediates/exploded-aar/com.android.support/support-v4/23.1.1/res:/Users/chen/Library/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/23.1.1/support-annotations-23.1.1.jar:/Users/chen/work/github/android/android-gpuimage/library/build/intermediates/classes/debug:/Users/chen/work/github/android/android-gpuimage/sample/build/intermediates/sourceFolderJavaResources/test/debug:/Users/chen/work/github/android/android-gpuimage/library/build/intermediates/sourceFolderJavaResources/debug:/Users/chen/work/github/android/android-gpuimage/sample/build/intermediates/sourceFolderJavaResources/debug:/Users/chen/work/github/android/android-gpuimage/build/generated/mockable-android-23.jar" com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 @w@/private/var/folders/vb/0fc4rm1n2vv82prbx340dj640000gn/T/idea_working_dirs_junit1.tmp @/private/var/folders/vb/0fc4rm1n2vv82prbx340dj640000gn/T/idea_junit1.tmp -socket58655
Exception in thread "main" java.lang.NoClassDefFoundError: junit/textui/ResultPrinter
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:122)
Caused by: java.lang.ClassNotFoundException: junit.textui.ResultPrinter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

Process finished with exit code 1

**Comment by cs8** [comment]
I choose open project not import project，It works.
