### ISSUE TITLE
java.lang.IllegalArgumentException: bitmap is recycled

### ISSUE THREAD

**Issue by cs8** [CyberAgent/android-gpuimage#306]
when I put GUPImage into a viewpager, sometime it's crashed. 
This is the error Log

at android.opengl.GLUtils.texImage2D(GLUtils.java:160)
at jp.co.cyberagent.android.gpuimage.OpenGlUtils.loadTexture(OpenGlUtils.java:49)
at jp.co.cyberagent.android.gpuimage.GPUImageRenderer$5.run(GPUImageRenderer.java:220)
at jp.co.cyberagent.android.gpuimage.GPUImageRenderer.onDrawFrame(GPUImageRenderer.java:113)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)

**Comment by jaysdev** [comment]
I got a same question. Do you find any solutions?

**Comment by cs8** [comment]
finally I use gpuimage-plus instand of it

**Comment by yefl2064** [comment]
I got a same question. Do you find any solutions?
