### ISSUE TITLE
Camera is being used after Camera.release() was called

### ISSUE THREAD

**Issue by dhagz** [CyberAgent/android-gpuimage#367]
Any idea to minimize this issue?

```
java.lang.RuntimeException: Camera is being used after Camera.release() was called
	at android.hardware.Camera.setPreviewTexture(Native Method)
	at jp.co.cyberagent.android.gpuimage.GPUImageRenderer$2.run(GPUImageRenderer.java:181)
	at jp.co.cyberagent.android.gpuimage.GPUImageRenderer.runAll(GPUImageRenderer.java:143)
	at jp.co.cyberagent.android.gpuimage.GPUImageRenderer.onDrawFrame(GPUImageRenderer.java:119)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java)
```

**Comment by mannan541** [comment]
@dhagz  having same issue. I called onPause() after capturing. Worked this for me!

**Comment by dhagz** [comment]
I got this issue when I released the camera during `onPause` and set-up again during `onResume`. Now, I only set-up the camera during `onCreate` and released during `onDestroy` which minimized this issue but gave birth to this issue: https://github.com/CyberAgent/android-gpuimage/issues/319
