### ISSUE TITLE
mGPUImage.saveToPictures("GPUImage", "ImageWithFilter.jpg", null); throws RuntimeException exception

### ISSUE THREAD

**Issue by developer--** [CyberAgent/android-gpuimage#369]
`java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                        at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                        at java.lang.Thread.run(Thread.java:818)`

**Comment by developer--** [comment]
than I changed saveToPictures method from GPUImage to GPUImageView saveToPictures method, but now nothing is happening

**Comment by mariusics** [comment]
Can you explain to me how to change that method ? I did not manage. I'm new in programming. Thank you.

**Comment by kuoliangkwong** [comment]
I'm having the same problem. 

` java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                          at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                          at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                          at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                          at java.lang.Thread.run(Thread.java:818)
                                                                       Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                          at jp.co.cyberagent.android.gpuimage.GPUImage.getBitmapWithFilterApplied(GPUImage.java:308)
                                                                          at jp.co.cyberagent.android.gpuimage.GPUImage$SaveTask.doInBackground(GPUImage.java:451)
                                                                          at jp.co.cyberagent.android.gpuimage.GPUImage$SaveTask.doInBackground(GPUImage.java:431)
                                                                          at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                          at java.lang.Thread.run(Thread.java:818) `

But the doc said GPUImage.saveToPictures is deprecated and suggested to use GPUImageView.saveToPictures. How do we use that?
